import React from "react";
import { SafeAreaView } from "react-native-safe-area-context";
import { View, Text, ScrollView, TouchableOpacity, Image } from "react-native";
// Asegúrate de que este archivo no tenga "pointerEvents" en sus estilos
import styles from "../styles/feedbackStyles.js";

const FeedbackScreen = ({ navigation }) => {
  const aiFeedbackData = {
    testMark: "0/10",
    questionsFeedback: [
      {
        id: 1,
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam at porttitor sem.",
        aiCorrection:
          "Gemini AI: Aquí fallaste porque olvidaste aplicar la ley de los signos...",
      },
      {
        id: 2,
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam at porttitor sem.",
        aiCorrection:
          "Gemini AI: Tu razonamiento fue bueno, pero el paso 3 requería una derivada...",
      },
    ],
  };

  return (
    // Usamos pointerEvents="auto" explícitamente solo si quieres forzar la interactividad,
    // pero por defecto no es necesario ponerlo.
    <SafeAreaView style={styles.container}>
      {/* HEADER */}
      <View style={styles.header}>
        <Text style={styles.logo}>Edusupernova</Text>
        <View style={styles.navLinks}>
          <Text style={styles.navItem}>Home</Text>
          <Text style={styles.navItem}>Subjects</Text>
          <Text style={styles.navItem}>Tests</Text>
        </View>
        <View style={styles.profileCircle} />
      </View>

      {/* ScrollView con contentContainerStyle para evitar errores de layout */}
      <ScrollView
        style={{ flex: 1 }}
        contentContainerStyle={styles.scrollContainer}
        showsVerticalScrollIndicator={false}
      >
        {/* TÍTULO Y NOTA */}
        <View style={styles.resultsHeader}>
          <Text style={styles.mainTitle}>Feedback Generated by AI:</Text>
          <Text style={styles.markLabel}>
            Test mark:{" "}
            <Text style={styles.markValue}>{aiFeedbackData.testMark}</Text>
          </Text>
        </View>

        {/* LISTADO DE FEEDBACK */}
        {aiFeedbackData.questionsFeedback.map((item) => (
          <View key={item.id.toString()} style={styles.feedbackBlock}>
            <Text style={styles.questionLabel}>QUESTION {item.id}:</Text>
            <Text style={styles.questionContent}>{item.text}</Text>

            <View style={styles.aiBox}>
              <Text style={styles.aiText}>{item.aiCorrection}</Text>
            </View>
          </View>
        ))}

        {/* BOTÓN HOME */}
        <TouchableOpacity
          style={styles.homeBtn}
          activeOpacity={0.8}
          onPress={() => navigation?.navigate("Home")}
        >
          <Text style={styles.homeBtnText}>Back to Home</Text>
        </TouchableOpacity>
      </ScrollView>
      {/* 6. FOOTER */}
      <View style={styles.footer}>
        <View>
          <Text style={styles.footerText}>Contact | About Us</Text>
          <Text style={styles.footerText}>Terms and Conditions</Text>
        </View>
        <View style={styles.socialIcons}>
          <Image
            source={require("../../assets/Instagram.png")}
            style={styles.icon}
          />
          <Image
            source={require("../../assets/LinkedInIcon.png")}
            style={styles.icon}
          />
          <Image
            source={require("../../assets/TikTokIcon.png")}
            style={styles.icon}
          />
        </View>
        <Text style={styles.footerText}>© 2026 Edusupernova</Text>
      </View>
    </SafeAreaView>
  );
};

export default FeedbackScreen;
